In [1]:
import numpy as np
import pandas as pd

# Data Extracting

In [3]:
df= pd.read_csv("Customer_Dataset.csv", sep=";")

In [4]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,...,Subscription Status,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Purchase Date,WeekdayNum,Weekday,Weekend,Churn
0,1,55,Male,Belt,Accessories,"46,9",Kentucky,L,Gray,Winter,...,Yes,Standard,0,14,Credit Card,7.01.2022,5,Friday,0,1
1,1,55,Male,Sweater,Clothing,"48,1",Kentucky,L,Green,Spring,...,Yes,Free Shipping,0,14,Credit Card,19.03.2022,6,Saturday,1,1
2,1,55,Male,Sweater,Clothing,"62,1",Kentucky,L,Green,Spring,...,Yes,Next Day Air,0,14,Debit Card,3.05.2022,2,Tuesday,0,1
3,1,55,Male,Belt,Accessories,"25,0",Kentucky,L,Turquoise,Summer,...,Yes,Free Shipping,0,14,Credit Card,7.05.2022,6,Saturday,1,1
4,1,55,Male,Sweater,Clothing,"89,8",Kentucky,L,Blue,Summer,...,Yes,2-Day Shipping,0,14,Google Pay,10.06.2022,5,Friday,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102766,3900,52,Female,Blouse,Clothing,"37,4",California,M,Brown,Winter,...,No,Standard,0,33,PayPal,1.12.2024,7,Sunday,1,0
102767,3900,52,Female,Blouse,Clothing,"66,0",California,M,Pink,Spring,...,No,Standard,0,33,Debit Card,20.12.2024,5,Friday,0,0
102768,3900,52,Female,Blouse,Clothing,"39,8",California,M,Maroon,Fall,...,No,Free Shipping,1,33,Debit Card,21.12.2024,6,Saturday,1,0
102769,3900,52,Female,Sneakers,Footwear,"90,7",California,M,Orange,Fall,...,No,2-Day Shipping,0,33,PayPal,22.12.2022,4,Thursday,0,0


In [5]:
df.shape

(102771, 21)

In [6]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Promo Code Used', 'Previous Purchases', 'Payment Method',
       'Purchase Date', 'WeekdayNum', 'Weekday', 'Weekend', 'Churn'],
      dtype='str')

# Data Tranformation

In [8]:
df.dtypes

Customer ID              int64
Age                      int64
Gender                     str
Item Purchased             str
Category                   str
Purchase Amount (USD)      str
Location                   str
Size                       str
Color                      str
Season                     str
Review Rating              str
Subscription Status        str
Shipping Type              str
Promo Code Used          int64
Previous Purchases       int64
Payment Method             str
Purchase Date              str
WeekdayNum               int64
Weekday                    str
Weekend                  int64
Churn                    int64
dtype: object

By checking data types i found 3 mismathced data types 
- purchage amount 
- Review Rating
- Purchage date

In [14]:
df.isnull().sum().sum()

np.int64(0)

There is no Missing values in a dataset

In [16]:
df.duplicated().sum()

np.int64(0)

And also there is no any Duplicate Values

# Changing Data Types

In [ ]:
df["Review Rating"] = (
    df["Review Rating"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float))

In [23]:
df["Purchase Date"] = pd.to_datetime(
    df["Purchase Date"],
    format="%d.%m.%Y")

In [29]:
df["Purchase Amount (USD)"] = (df["Purchase Amount (USD)"]
    .astype(str)
    .str.replace(",", ".", regex=False)
    .astype(float))

In [30]:
df.dtypes

Customer ID                       int64
Age                               int64
Gender                              str
Item Purchased                      str
Category                            str
Purchase Amount (USD)           float64
Location                            str
Size                                str
Color                               str
Season                              str
Review Rating                   float64
Subscription Status                 str
Shipping Type                       str
Promo Code Used                   int64
Previous Purchases                int64
Payment Method                      str
Purchase Date            datetime64[us]
WeekdayNum                        int64
Weekday                             str
Weekend                           int64
Churn                             int64
Purchase Amount                 float64
dtype: object

# Chacking incoorect Values

In [31]:
df["Gender"].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

In [32]:
df["Category"].unique()

<ArrowStringArray>
['Accessories', 'Clothing', 'Outerwear', 'Footwear']
Length: 4, dtype: str

In [33]:
df["Season"].unique()

<ArrowStringArray>
['Winter', 'Spring', 'Summer', 'Fall']
Length: 4, dtype: str

In [34]:
df["Subscription Status"].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [35]:
df["Promo Code Used"].unique()

array([0, 1])

In [36]:
df["Weekend"].unique()

array([0, 1])

In [37]:
df["Churn"].unique()

array([1, 0])